# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Explosion_script.py
# Created on: 2018-01-23 16:39:59.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Explosion_script <Input_Features> <Distance__value_or_field_> <Layer> <Intersect_shp> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Features = arcpy.GetParameterAsText(0)

Distance__value_or_field_ = arcpy.GetParameterAsText(1)

Layer = arcpy.GetParameterAsText(2)

Intersect_shp = arcpy.GetParameterAsText(3)
if Intersect_shp == '#' or not Intersect_shp:
    Intersect_shp = "M:\\All_GIS_work\\Programming2\\Week1\\Intersect.shp" # provide a default value if unspecified

# Local variables:
Output_Feature_Class = "M:\\All_GIS_work\\Programming2\\Week1\\buff.shp"

# Process: Buffer
arcpy.Buffer_analysis(Input_Features, Output_Feature_Class, Distance__value_or_field_, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis([Layer, Output_Feature_Class], Intersect_shp, "ALL", "", "INPUT")

